changelog:
  exclude:
    labels:
      - "skip:changelog"
  categories:
    - title: Breaking Changes
      labels:
        - "type:breaking"
    - title: Enhancements
      labels:
        - "type:enhancement"
        - "type:new-feature"
    - title: Internal Improvements
        - "type:internal-improvements"
    - title: Bug Fixes
        - "type:bug"
    - title: Other Changes
      labels:
        - "*"
