language: c
sudo: false
branches:
        except:
                - todo
matrix:
    include:
        - compiler: gcc
          env: CFLAGS="-g -O2 -Wall -Wpointer-arith -fno-strict-aliasing -Werror -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-type-limits -Wno-missing-field-initializers"
        - compiler: clang
          env: CFLAGS="-g -O2"
addons:
    apt:
            packages:
                    - autotools-dev
                    - build-essential
                    - debhelper
                    - dh-autoreconf
                    - file
                    - fontconfig
                    - gettext
                    - libfontconfig-dev
                    - libfreetype6-dev
                    - libfribidi-dev
                    - libncurses5-dev
                    - libpng-dev
                    - libreadline-dev
                    - libsm-dev
                    - libx11-dev
                    - libxcursor-dev
                    - libxext-dev
                    - libxft-dev
                    - libxi-dev
                    - libxpm-dev
                    - libxrandr-dev
                    - libxrender-dev
                    - libxt-dev
                    - sharutils
                    - xsltproc
script: (./autogen.sh && CFLAGS= ./configure) && make
notifications:
        irc:
                channels:
                        - "chat.freenode.net#fvwm"
                use_notice: true
                skip_join: true
