#!/bin/sh
#
# Replaces the commands xmkmf; make Makefiles for my broken setup.
#

FVWMSRCDIR=`pwd`
echo FVWMSRCDIR is $FVWMSRCDIR

echo Making top-level Makefile
xmkmf
echo done

for i in libs fvwm xpmroot utils sample.fvwmrc modules/*
do
echo Making Makefile in $i
cd $i ; xmkmf ; make depend ; cd $FVWMSRCDIR
echo done
done


