.\" t
.\" @(#)FvwmBanner.1	1/12/94
.de EX		\"Begin example
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 1
.if t .sp .5
..
.TH FvwmBanner 1 "23 September 2002" FVWM "FVWM Modules"
.UC
.SH NAME
FvwmBanner \- the FVWM Banner module
.SH SYNOPSIS
Module FvwmBanner

\fIFvwmBanner\fP can only be invoked by fvwm.
Command line invocation of the \fIFvwmBanner\fP module will not work.

.SH DESCRIPTION
FvwmBanner displays an Fvwm Logo in the center of the screen
for 3 seconds.

.SH COPYRIGHTS
None.

.SH INITIALIZATION
Nothing interesting.

.SH INVOCATION
FvwmBanner can be invoked by the command 'Module FvwmBanner'.
This can be bound to
a menu or key-stroke in the .fvwm2rc file,
but more likely you would do this in the StartFunction or InitFunction,
for example:
.EX
AddToFunc InitFunction "I" Module FvwmBanner
.EE

You can also give it an
optional file parameter, like 'FvwmBanner doomface.xpm' or specify an
alternate default pixmap via configuration options
(see "*FvwmBanner: Pixmap" below).
Fvwm will search the ImagePath
to find the image, or you can use the full path to the image.

.SH CONFIGURATION OPTIONS

.IP "*FvwmBanner: NoDecor"
Tells FvwmBanner to create a window that Fvwm will not manage and not decorate.

.IP "*FvwmBanner: Pixmap \fIfile\fP"
Tells FvwmBanner to display \fIfile\fP instead of the built in pixmap.

.IP "*FvwmBanner: Timeout \fIsec\fP"
Tells FvwmBanner to display for \fIsec\fP seconds instead of default
of 3 seconds.

.SH AUTHOR
Robert Nation
