.\" t
.\" @(#)FvwmTaskBar.1	6/30/96
.TH FvwmTaskBar 1 "7 May 1999"
.UC
.SH NAME
FvwmTaskBar \- the FVWM taskbar module
.SH SYNOPSIS
FvwmTaskBar is spawned by FVWM, so no command line invocation will work.

.SH DESCRIPTION
The FvwmTaskBar module provides a taskbar made up of buttons arranged by
rows, each corresponding to a window that FVWM is managing.
Clicking on first button gives focus to the corresponding top level window;
clicking on the middle button will hide a top level window; third mouse button
is reserved for a future extension (context menu).
Like the other modules, FvwmTaskBar only works when fvwm is used as the
window manager.

When started, the taskbar shows up as a single row of buttons filling the
full width of the screen, but during the work can be resized to accommodate
up to 8 rows. In addition, if the AutoStick option is used, the taskbar
will auto position itself at the top or bottom of the screen, and can be
dragged from one position to another with a normal move operation.

The first button of the taskbar, labelled "Start" sends a "Popup
StartMenu" command to the FVWM, which can be used to pop-up a
general-purpose menu when the button is pressed.

The FvwmTaskBar also displays at the right side a window showing the
current time and the built-in incoming mail indicator.

.SH COPYRIGHTS
The FvwmTaskBar module is derived from Mike Finger's FvwmWinList.

Copyright 1994, Mike Finger. The author makes no guarantees or warranties of
any kind about the use of this module.  Use this modules at your own risk.
You may freely use this module or any portion of it for any purpose as long
as the copyright is kept intact.

.SH INITIALIZATION
During initialization, \fIFvwmTaskBar\fP gets configuration information
from FVWM to find the options that pertain to it.
These options are discussed in a later section.

.SH INVOCATION
FvwmTaskBar can be invoked by fvwm during initialization by inserting the
line 'Module FvwmTaskBar' in the .fvwm2rc file.

FvwmTaskBar must reside in a directory that is listed in the ModulePath
option of FVWM for it to be executed by FVWM.

.SH CONFIGURATION OPTIONS
The following options can be placed in the .fvwm2rc file

.IP "*FvwmTaskBarGeometry \fI{+-}<X>{+-}<Y>\fP"
Specifies the location and gravity of the FvwmTaskBar window.
Currently, this option is scanned as a normal X geometry string.
You can include the width and the height in addition to the "x" and
"y" offset.  However, only the "x" and "y" offset are used.
To avoid possible future compatibility problems, only code the "x" and
"y" offset.

The actual width of the taskbar is always the full width of the screen
and the height is controlled by the *FvwmTaskBarRows option.

If the AutoStick option
is specified, the taskbar automatically "sticks" to the top or
the bottom of the screen, whichever is closest to the geometry specification.

To position the taskbar at the bottom of the screen, use a geometry of
"+0-0".

.IP  "*FvwmTaskBarRows r"
Specifies the initial number in rows of the FvwmTaskBar window. Default
is 1 and the maximum is 8.

.IP "*FvwmTaskBarFont \fIfont\fP"
Specifies the default font to be used for labeling the buttons, when they
are not depressed. If not specified, fixed font is assumed.

.IP "*FvwmTaskBarSelFont \fIfont\fP"
Specifies the font to be used for the depressed buttons. Note that the
Start button will use always this font even if is not pressed. If this
option is not specified, the default font is used instead.

.IP "*FvwmTaskBarStatusFont \fIfont\fP"
Specifies the font to be used for the clock and tip windows. If this
option is not specified, fixed font is used.

.IP "*FvwmTaskBarFore \fIcolor\fP"
Specifies the color to use for the button names.

.IP "*FvwmTaskBarBack \fIcolor\fP"
Specifies the background color for the bar and buttons.

.IP "*FvwmTaskBarColorset \fIcolorset\fP"
Tells the module to use colorset \fIcolorset\fP for the window
background and the foreground color of the buttons.  Please refer
to the man page of the FvwmTheme module for details about colorsets.

.IP "*FvwmTaskBarIconFore \fIcolor\fP"
Specifies the color to use for the button names which represent iconified
windows.

.IP "*FvwmTaskBarIconBack \fIcolor\fP"
Specifies the color to use for the buttons which represent iconified windows.

.IP "*FvwmTaskIconColorset \fIcolorset\fP"
Tells the module to use colorset \fIcolorset\fP for the
buttons of iconified windows.  Please refer to the man page of
the FvwmTheme module for details about colorsets.

.IP "*FvwmTaskBarFocusFore \fIcolor\fP"
Specifies the color to use for the button which represents the window
with the focus.  If not specified the color specified by *FvwmTaskBarFore or
*FvwmTaskBarColorset is used.

.IP "*FvwmTaskBarFocusBack \fIcolor\fP"
Specifies the color to use for the button which represents the window
with the focus. If not specified the color specified by  *FvwmTaskBarBack or
*FvwmTaskBarColorset is used. Note that the button which represents the window
with the focus is also highlighted.  See "*FvwmTaskNoBrightFocus".

.IP "*FvwmTaskBarFocusColorset \fIcolorset\fP"
Tells the module to use colorset \fIcolorset\fP for the button
which represents the window with the focus. Please refer to the man page of
the FvwmTheme module for details about colorsets.

.IP "*FvwmTaskBarNoBrightFocus"
By default the button which represents the window with the focus is
highlighted. This option disables this feature.  \fINote:\fP uou will
want this option if you use a pixmap (via FvwmTheme) for the background.

.IP "*FvwmTaskBarTipsFore \fIcolor\fP"
Specifies the color to be used for the text in the tips windows.

.IP "*FvwmTaskBarTipsBack \fIcolor\fP"
Specifies the background color for the tips windows.

.IP "*FvwmTaskTipsColorset \fIcolorset\fP"
Tells the module to use colorset \fIcolorset\fP for the tips windows.  
Please refer to the man page of the FvwmTheme module for details about 
colorsets.

.IP "*FvwmTaskBarAutoStick"
This option causes the taskbar to "stick" either to the top or bottom
of the screen, whichever is closest to the initial window placement. Any
further move operation is also subject to that behavior.

.IP "*FvwmTaskBarAutoFocus"
This option causes the taskbar to raise a window if the cursor stays on a
button in taskbar and its tip is open.

.IP "*FvwmTaskBarAutoHide"
This option causes the taskbar to disappear leaving a narrow strip at the
bottom of the screen, and reappear only when the mouse is moved to that
strip.  This option automatically enables AutoStick.

.IP "*FvwmTaskBarUseSkipList"
Tells FvwmTaskBar to not show the windows that are listed on a WindowListSkip
line in the configuration file.

.IP "*FvwmTaskBarDeskOnly"
Tells FvwmTaskBar to show the windows that are only on the current desktop.
When desktops are switched, the list of windows changes accordingly.

.IP "*FvwmTaskBarUseIconNames"
Tells FvwmTaskBar to use the icon name of the window instead of the full
window name.  This is useful to keep the width of the buttons small.

.IP "*FvwmTaskBarShowTransients"
Tells FvwmTaskBar to show the application transient windows also. By default
they are not shown.

.IP "*FvwmTaskBarAction \fIaction response\fP"
Tells FvwmTaskBar to do \fIresponse\fP when \fIaction\fP is done.  The
currently supported \fIaction\fPs are: Click1, Click2, Click3.  The currently
supported \fIresponse\fPs are any fvwm built-in commands, including modules
and functions.  Warning: Use of the former syntax that allowed to use comma
separated lists of commands is strongly discouraged due to synchronization
problems with fvwm.  Please use complex fvwm functions instead (defined with
the AddToFunc command of fvwm).

.IP "*FvwmTaskBarButtonWidth \fIwidth\fP"
Indicates the maximum width that window buttons should reach.
(the minimum is hard coded at 32).

.IP "*FvwmTaskBar3DFvwm"
By default the buttons use a special (asymetric) 3D look. This option enables
a more classical 3D look (Ie., a la fvwm).

.IP "*FvwmTaskBarHighlightFocus"
If the mouse pointer is over the taskbar, the window under the current
button is active. This behavior is like the TVTWM Icon Manager or
FvwmIconMan. \fINote:\fP If you use this option combined with FollowMouse
focus style, you'll want the taskbar to be ClickToFocus.

.IP "*FvwmTaskBarShowTips"
Enables the tips windows (by default disabled).

.IP "*FvwmTaskBarNoIconAction \fIaction\fP"
Tells FvwmTaskBar to do \fIaction\fP is when a NoIcon style window is
iconified or de-iconified. Relevant coordinates are appended to \fIaction\fP so
that the icon can be traced to an FvwmTaskBar button. An example action
is "*FvwmTaskBarNoIconAction SendToModule FvwmAnimate animate". A blank or null
action turns this feature off.

.SH ""

The following options deal more specifically with the status indicators
displayed at the right of the taskbar.

.IP "*FvwmTaskBarClockFormat \fIformat-string\fP"
This option specifies the time format for the digital clock.
It is a \fIstfrtime(3)\fP compatible format string.
By default it is "%R".

.IP "*FvwmTaskBarUpdateInterval \fIseconds\fP"
Specifies how often the clock display should be refreshed, so that times of
the form HH:MM:SS can be used. By default 60 seconds.

.IP "*FvwmTaskBarBellVolume \fIvolume\fP"
This sets the volume of the bell when mail is detected.
It is a value between 0 (no bell) and 100 (maximum volume).
By default it is set to 20.

.IP "*FvwmTaskBarMailBox \fIpath\fP"
This option instructs the module to look for mail at the specified place
It is a full pathname to the user's mailbox.
By default it is \fI/var/spool/mail/$USER_LOGIN\fP.
A value of 'None' instructs the module not to have a mail indicator.

.IP "*FvwmTaskBarMailCommand \fIcommand\fP"
Specifies a \fIfvwm\fP command to be executed when double-clicking
on the mail icon.

.IP "*FvwmTaskBarMailCheck \fIseconds\fP"
Specifies the interval between checks for new mail. The default is
ten seconds. A value of zero or less switches mail checking off.

.IP "*FvwmTaskBarIgnoreOldMail"
If set, draw no bitmap if there is no new mail.

.SH ""
The following options deal with the Start button at the left of the taskbar:

.IP "*FvwmTaskBarStartName \fIstring\fP"
This option specifies the string displayed in the Start button.
('Start' by default).

.IP "*FvwmTaskBarStartMenu \fIstring\fP"
This option specifies the pop up menu to invoke when the start button is
pressed. ('StartMenu' by default). The module send a 'Popup StartMenu'
command to the fvwm window manager.

.IP "*FvwmTaskBarStartIcon \fIicon-name\fP"
This option specifies the name of the icon to display at the left of the Start
button.

.SH SAMPLE CONFIGURATION
The following are excepts from a .fvwm2rc file which describe FvwmTaskBar
initialization commands:

.nf
.sp
#
# Start the taskbar on fvwm startup and restart
#

AddToFunc "StartFunction" "I" Module FvwmTaskBar

#
# For Click 1 action
#

AddToFunc DeiconifyRaiseAndFocus
+ I Iconify off
+ I Raise
+ I Focus

#
# Set the style for the taskbar window, keep always on top of another
# windows
#

Style "FvwmTaskBar" NoTitle,BorderWidth 4, HandleWidth 4,Sticky,
StaysOnTop,WindowSkipList,CirculateSkip

#------------------------------------ taskbar
*FvwmTaskBarBack #c3c3c3
*FvwmTaskBarFore black
*FvwmTaskBarTipsBack bisque
*FvwmTaskBarTipsFore black
*FvwmTaskBarGeometry +0-0
*FvwmTaskBarFont -adobe-helvetica-medium-r-*-*-14-*-*-*-*-*-*-*
*FvwmTaskBarSelFont -adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*
*FvwmTaskBarStatusFont fixed

*FvwmTaskBarAction Click1 DeiconifyRaiseAndFocus
*FvwmTaskBarAction Click2 Iconify On
*FvwmTaskBarAction Click3 Lower

*FvwmTaskBarUseSkipList
*FvwmTaskBarUseIconNames
*FvwmTaskBarAutoStick
*FvwmTaskBarShowTips
*FvwmTaskBarNoIconAction SendToModule FvwmAnimate animate

*FvwmTaskBarButtonWidth 180
*FvwmTaskBarBellVolume 20
*FvwmTaskBarMailBox /var/spool/mail/
*FvwmTaskBarMailCommand Exec xterm -e mail
*FvwmTaskBarClockFormat %I:%M %p

*FvwmTaskBarStartName Start
*FvwmTaskBarStartMenu StartMenu
*FvwmTaskBarStartIcon mini-exp.xpm

.sp
.fi

.SH BUGS
There is a bug report that FvwmTaskBar doesn't work well with
auto hide turned on.

.SH AUTHOR
.IP "\fIDavid Barth\fP <barth@di.epfl.ch>"

.SH ACKNOWLEDGMENTS
These people have contributed to \fBFvwmTaskBar\fP:

.IP "\fIDanny Dulai\fP <nirva@ishiboo.com>"
