.\" t
.\" @(#)FvwmTheme.1  7/20/1999
.TH FvwmTheme 1 "20 July 1999"
.UC

.SH NAME
FvwmTheme \- an FVWM modules for managing the appearance of FVWM and its modules

.SH SYNOPSIS
FvwmTheme is spawned by fvwm, so no command line invocation will work.

.SH COPYRIGHT
Copyright (C) 1999 Joey Shutup.  No guarantees or warranties or anything are
provided or implied in any way whatsoever.  Use this program at your own risk.
Permission to use this program for any purpose is given, as long as the
copyright is kept intact.

.SH DESCRIPTION
FvwmTheme creates appearance resources that may be shared by FVWM and other
modules.  It reads an initial configuration and also reacts to configuration
commands and mesages sent from FVWM so that the resources can be dynamically
changed.

.SH INVOCATION
FvwmTheme must be spawned as a module by fvwm.
.PP
It is important that FvwmTheme is invoked before any other modules
that use the color sets provided by FvwmTheme.  Thus FvwmTheme has
to be invoked with the 'ModuleSynchronous' command by inserting the
line 'ModuleSynchronous Timeout 5 FvwmTheme' in the .fvwm2rc file
right after the \fIModulePath\fP and \fIImagePath\fP have been defined.
Invoking FvwmTheme from the \fIInitFunction\fP, \fIStartFunction\fP
or\fIRestartFunction\fP or later may not work properly and can
cause excessive redrawing of already running modules.  It is important
that the configuration lines for FvwmTheme appear in the configuration
file before FvwmTheme is started.  You can find a proper sample
fvwm setup at the end of this document.  Fvwm will search the
directory specified in the ModulePath configuration option to attempt
to locate FvwmTheme.  It is pointless to run more than one FvwmTheme
so there is no provision for using an alias name.

.SH CONFIGURATION OPTIONS
FvwmTheme supports some configuration options.

.IP "*FvwmThemeColorset \fIn\fP \fIoptions\fP "
Will create or modify colorset \fIn\fP. Each colorset has four colors, an
optional pixmap and an optional shape mask.  The four colors are used by
modules as the foreground, background, highlight and shadow colors.  When
a colorset is created the colors from colorset 0 are copied (these are,
also controlled by the DefaultColors fvwm command).

Warning: The highest colorset number used determines memory consumption.
Thus if you define 'Colorset 100000', the memory for 100001 colorsets will
be used.  Keep your colorset numbers as small as possible.

\fIoptions\fP is a coma separated list containing some of the keywords:
fg, Fore, Foreground, bg, Back, Background, hi, Hilite, Hilight, sh,
Shade, Shadow, Pixmap, TiledPixmap, AspectPixmap, Shape, TiledShape,
AspectShape and ?Gradient.

\fIfg\fP, \fIFore\fP and \fIForeground\fP take a color name as an argument and
set the foreground color.  The special name \fIConstrast\fP may be used to
select a color that contrasts well with the background color.  To reset
the foreground color to the default value you can simply omit the color
name.

\fIbg\fP, \fIBack\fP and \fIBackground\fP take a color name as an argument and
set the background color.  It also sets the highlight and shadow colors to
values that give a 3d effect unless these have been explicitly set with the
options below.  The special name \fIAverage\fP may be used to select a color
that is the average color of the pixmap.  The background color is reset to
the default value if the color name is omitted.

\fIhi\fP, \fIHilite\fP and \fIHilight\fP take a color name as as argument and
set the highlight color.  If the hilight color is not explicitly set,
the default is to calculate it from the background color.  To switch back
to the default behaviour the color name can be omitted.

\fIsh\fP, \fIShade\fP and \fIShadow\fP take a color name as as argument and
set the shadow color.  If the shadow color is not explicitly set,
the default is to calculate it from the background color.  To switch back
to the default behaviour the color name can be omitted.

\fIPixmap\fP, \fITiledPixmap\fP and \fIAspectPixmap\fP take a file name as
an argument, search the \fIImagePath\fP and use it as the background pixmap.
Any transparent parts are filled with the background color.  Not specifying a
file name removes any existing one from the colorset.  \fITiledPixmap\fP will
produce repeated copies of the image with no scaling, \fIPixmap\fP will
cause the image to be stretched to fit whatever object the colorset is applied
to and \fIAscpectPixmap\fP will stretch to fit but will retain the image
aspect ratio.  Bitmaps are not supported.

\fIShape\fP, \fITiledShape\fP and \fIAspectShape\fP take a file name as
an argument, search the \fIImagePath\fP and use it as the shape bitmap.
\fITiledShape\fP will produce repeated copies of the bitmap with no scaling,
\fIShape\fP will cause the bitmap to be stretched to fit whatever object the
colorset is applied to and \fIAscpectShape\fP will stretch to fit but will
retain the bitmap aspect ratio.  If the file is a pixmap in xpm format,
the shape mask of the pixmap is used.

Warning: Due to the way X11 implements shapes and the implementation
of the FvwmTheme module you cannot take back making windows shaped.
You may have to restart fvwm or the shaped application.

\fI?Gradient ...\fP will create a pixmap and stretch it to fit the window.
\fI?Gradient\fP may be one of Hgradient, Vgradient, Dgradient, Bgradient,
Sgradient, Cgradient, Rgradient or Ygradient.  The gradient types are as
follows:  H is horizontal; V is vertical; D is diagonal from top left to
bottom right; B is a backwards diagonal from bottom left to top right; S
is concentric squares; C is con-centric circles; R is a radar like pattern
and Y is a Yin Yang style (but without the dots, we are not \fIthat\fP mad).
Please refer to the \fICOLOR GRADIENTS\fP section in the \fIfvwm2\fP man page
for the syntax of gradients.

.IP "*FvwmThemeReadWriteColors"
Tells FvwmTheme to use read/write color cells for the foreground and background
pixels.  This can make changing colorsets much faster but can only be used with
PseudoColor displays.  This option must be specified first and it cannot be
turned off.  If the pixmap and shape of a colorset are unchanged modules
do not redraw when the colors are changed.

.SH COMMANDS
The following FVWM command may be executed at any time to alter the colorsets.
It may be bound to a menu item or typed into a module such as FvwmConsole.

.IP "SendToModule FvwmTheme Colorset \fIoptions\fP"
The syntax is the same as the configuration option.

.SH EXAMPLES

.in +.3i
*FvwmThemeColorset 3 fg wheat, bg navy
.in -.3i

If necessary this will create colorsets 0, 1, 2 and 3 and then change colorset
3 to have a foreground of wheat, a background of navy.

.in +.3i
*FvwmThemeColorset 3 bg "navy blue"
.in -.3i

will change the background color of colorset 3 to navy blue. The foreground and
pixmap will be unchanged.

.in +.3i
*FvwmThemeColorset 3 AspectPixmap \\
  large_murky_dungeon.xpm
.in -.3i

will cause depression

.in +.3i
*FvwmThemeColorset 3 bg Average
.in -.3i

will set the background color and the relief colors to match the background
pixmap.

.in +.3i
*FvwmThemeColorset 3 YGradient 200 3 \\
  blue 1000 navy 1 blue 1000 navy
.in -.3i

will add a Yin Yang gradient background pixmap to colorset 3.  If the
background is set to average it will be recomputed as will the foreground
if that is set to contrast.

.EX
 #!/bin/sh
 FvwmCommand "SendToModule FvwmTheme Colorset 7
   fg navy, bg gray"
 while true
 do
   FvwmCommand "SendToModule FvwmTheme Colorset 7
     fg gray"
   sleep 1
   FvwmCommand "SendToModule FvwmTheme Colorset 7
     fg navy"
   sleep 1
 done
.EE

will make colorset 7 blink if used with the *FvwmThemeReadWriteColors option.

The color names used in color sets can be substituted in any fvwm
command.  Please refer to the \fICOMMAND LINE PARAMETER EXPANSION\fP
section in the fvwm2 man page and the example below for a description.

.SH SAMPLE FVWM CONFIGURATION

Below you can find a fvwm configuration file that demonstrates the
use of the FvwmTheme module.  The order in which FvwmTheme and the
other modules are configured and started is important.

.EX
 # fvwm paths
 ModulePath <put your module path here>
 ImagePath <put your image path here>

 #
 # FvwmTheme
 #
 # The FvwmTheme setup must be first in the config file,
 # right after the paths are set.
 #
 # Instead of the *FvwmThemeColorset... lines below you
 # could read in a file with these commands.  So to change
 # your color scheme you can simply copy a different file
 # over your palette file and restart fvwm:
 #
 # Read /home/my_user_name/.fvwm2_palette
 #

 # 0 = Default colours
 # 1 = Inactive windows
 # 2 = Active windows
 # 3 = Inactive menu entry and menu background
 # 4 = Active menu entry
 # 5 = greyed out menu entry (only bg used)
 # 6 = module foreground and background
 # 7 = hilight colours
 *FvwmThemeColorset 0 fg black, bg rgb:b4/aa/94
 *FvwmThemeColorset 1 fg black, bg rgb:a1/b2/c8
 *FvwmThemeColorset 2 fg black, bg rgb:da/9a/68
 *FvwmThemeColorset 3 fg black, bg rgb:b4/aa/94, \\
   VGradient 100 dtcolour5 rgb:b4/aa/94
 *FvwmThemeColorset 4 fg black, bg rgb:b4/aa/94
 *FvwmThemeColorset 5 fg rgb:d2/bf/a8, \\
   bg rgb:b4/aa/94
 *FvwmThemeColorset 6 fg black, bg rgb:b4/aa/94, \\
   VGradient 100 dtcolour5 rgb:b4/aa/94
 *FvwmThemeColorset 7 fg black, bg rgb:94/ab/bf

 # run FvwmTheme before anything else is done
 ModuleSynchronous Timeout 5 FvwmTheme

 #
 # general setup
 #
 Style * ForeColor $[fg.cs1]
 Style * BackColor $[bg.cs1]
 HilightColor $[fg.cs2] $[bg.cs2]
 MenuStyle * MenuColorset 3
 MenuStyle * ActiveColorset 4
 MenuStyle * GreyedColorset 5

 #
 # Applications
 #
 AddToFunc InitFunction
 + I Exec exec xterm -fg $[fg.cs0] -bg $[bg.cs0]

 #
 # module setup
 #

 # ... more FvwmPager config lines ...
 *FvwmPagerColorset * 6
 *FvwmPagerBalloonColorset * 6
 *FvwmPagerHilightColorset * 7
 *FvwmPagerWindowColorsets 1 2

 # ... more FvwmIconMan config lines ...
 *FvwmIconMan*Colorset 6
 *FvwmIconMan*FocusColorset 2
 *FvwmIconMan*FocusAndSelectColorset 2
 *FvwmIconMan*PlainColorset 6
 *FvwmIconMan*SelectColorset 6
 *FvwmIconMan*TitleColorset 6

 # ... more FvwmButtons config lines ...
 *FvwmButtonsFore     $[fg.cs6]
 *FvwmButtonsBack     $[bg.cs6]
 *FvwmButtonsColorset 6
 # sample button passing color to xterm
 *FvwmButtons(Title xterm, \\
   Action "Exec exec xterm -fg $[fg.cs6] -bg[bg.cs6")

 # ... more FvwmWharf config lines ...
 *FvwmWharfColorset 6

 # ... more FvwmIdent config lines ...
 *FvwmIdentColorset 6

 # ... more FvwmWinList config lines ...
 *FvwmWinListColorset      1
 *FvwmWinListFocusColorset 2
 *FvwmWinListIconColorset  1

 # ... more FvwmTaskBar config lines ...
 *FvwmTaskBarColorset     6
 *FvwmTaskBarIconColorset 6
 *FvwmTaskBarTipsColorset 0
.EE

.SH BUGS

Initialisation of fvwm, FvwmTheme and the other modules is tricky.
Please pay close attention to the text in the \fIINVOCATION\fP
section.  The example above demonstrates the proper way to get a
FvwmTheme setup running.

.SH AUTHOR

Prefers to remain anonymous.
With help from Brad Giaccio and Dominik Vogt.
