.\" t
.\" @(#)FvwmTheme.1  7/20/1999
.TH FvwmTheme 1 "20 July 1999"
.UC

.SH NAME
FvwmTheme \- an FVWM modules for managing the appearance of FVWM and its modules

.SH SYNOPSIS
FvwmTheme is spawned by fvwm, so no command line invocation will work.

.SH COPYRIGHT
Copyright (C) 1999 Joey Shutup.  No guarantees or warranties or anything are
provided or implied in any way whatsoever.  Use this program at your own risk.
Permission to use this program for any purpose is given, as long as the
copyright is kept intact.

.SH DESCRIPTION
FvwmTheme creates appearance resources that may be shared by FVWM and other
modules.  It reads an initial configuration and also reacts to configuration
commands and mesages sent from FVWM so that the resources can be dynamically
changed.

.SH INVOCATION
FvwmTheme must be spawned as a module by fvwm.
.PP
It is important that FvwmTheme is invoked before any other modules
that use the color sets provided by FvwmTheme.  Thus FvwmTheme has
to be invoked with the 'ModuleSynchronous' command by inserting the
line 'ModuleSynchronous Timeout 10 FvwmTheme' in the .fvwm2rc file.
This can be placed on a line by itself, if FvwmTheme is to be
spawned during fvwm's initialization.  It can be started from fvwm's
StartFunction too and should then be the first command executed.
Invoking FvwmTheme later may not work properly
and can cause excessive redrawind of already running modules.
Fvwm will search the directory specified in the ModulePath
configuration option to attempt to locate FvwmTheme. It is pointless
to run more than one FvwmTheme so there is no provision for using an
alias name.

.SH CONFIGURATION OPTIONS
FvwmTheme supports only one configuration option.

.B "*FvwmThemeColorset" "\fIn\fP \fIfg\fP \fIbg\fP [\fIshape option\fP] [\fIpixmap option\fP]"
Will create or modify colorset \fIn\fP. Each colorset has a foreground and
background color specified by \fIfg\fP and \fIbg\fP respectively.  If
either \fIfg\fP or \fIbg\fP is specified as "-" it is not altered. If \fIbg\fP
is specified as "average" it is calculated as the average color of the
backround pixmap. Colors may be specified by name e.g. Liver or "Fava bean" or
as an RGB hexadecimal triplet "#RRGGBB" e.g. "#551111" for a nice Chianti.

Each colorset may also have a pixmap associated with it as an adjunct to the
background color.  This may be used instead of the background color and should
have roughly the same average color as the background so that any 3D bevels
(which are calculated from the background color) don't look strange.
The background color is used for the transparent parts of the pixmap.

The optional pixmap may be specified as "TiledPixmap \fIxpm\fP",
"Pixmap \fIxpm\fP", "AspectPixmap \fIxpm\fP" or "\fI?Gradient...\fP". \fIxpm\fP
is the filename of an XPM format file. FvwmTheme will search the current
\fIImagePath\fP for the file. \fITiledPixmap\fP causes the pixmap to be tiled
onto the background, \fIPixmap\fP will stretch the pixmap to the size of the
window and \fIAspectPixmap\fP will stretch the pixmap whilst preserving the
aspect ratio.

An optional shape pixmap can be used to shape the background of the
window it is applied to and thus the window itself. "Shape \fIpicture\fP",
"TiledShape \fIpicture\fP" and "AspectShape \fIpicture\fP" do roughly
the same as the pixmap options above. One difference is that only the
mask of a xpm picture is used, i.e. all pixels that are transparent in
the xpm will be transparent in the window. If the picture is a bitmap
with only two colors, this bitmap is used as the mask. Note that the
shape will create holes in the window it is applied to. The masked
parts are not simply transparent.

\fI?Gradient ...\fP will create a pixmap and stretch it to fit the window.
\fI?Gradient\fP may be one of HGradient, VGradient, DGradient, BGradient,
SGradient, CGradient, RGradient or YGradient.  The gradient types are as
follows:  H is horizontal; V is vertical; D is diagonal from top left to
bottom right; B is a backwards diagonal from bottom left to top right; S
is concentric squares; C is con-centric circles; R is a radar like pattern
and Y is a Yin Yang style (but without the dots).  Please refer to the
\fICOLOR GRADIENTS\fP section in the \fIfvwm2\fP man page for the syntax
of gradients.

.SH COMMANDS
The following FVWM command may be executed at any time to alter the colorsets.
It may be bound to a menu item or typed into a module such as FvwmTalk.

.IP "SendToModule FvwmTheme Colorset \fIn\fP \fIfg\fP \fIbg\fP [ \fIoption\fP... ]"
The syntax is the same as the configuration option.

.SH EXAMPLES

*FvwmThemeColorset 3 black gray

If necessary this will create colorsets 0, 1, 2 and 3 and then change colorset
3 to have a foreground of black, a background of gray and delete the optional
pixmap.

*FvwmThemeColorset 3 - "navy blue" -

Will change the background color of colorset 3 to navy blue. The foreground and
pixmap will be unchanged.

*FvwmThemeColorset 3 - - YGradient 200 3 blue 49 navy 1 blue 50 navy

Will add a Yin Yang gradient background pixmap to colorset 3.

