.TH FVWM24_CONVERT 1 "25 September 2000"
.SH NAME

fvwm24_convert \- convert FVWM 2.2x configuration file to FVWM 2.4x syntax
.SH SYNOPSIS

.BI fvwm24_convert " source dest"
.SH DESCRIPTION

.B fvwm24_convert
converts an FVWM 2.2x configuration
file into an FVWM 2.4x compatible syntax.
.PP
By default,
.B fvwm24_convert
converts
.I ~/.fvwm2rc,
saving the
results in
.I ~/.fvwm/.fvwm2rc.
You must create the
.I ~/.fvwm
directory before running this command.
Starting with the 2.4 release, the directory
.I ~/.fvwm
is the default
location for fvwm user configuration files.
Different source and destination files
may be given.
If the destination file already exists, this program exits.
.PP
.B fvwm24_convert
makes the following changes:
.TP 4
.B PixmapPath/IconPath
In fvwm 2.4x, the PixmapPath and IconPath commands are replaced by
the ImagePath command.  In addition, the ImagePath can be compiled into
fvwm.
.B fvwm24_convert
changes the PixmapPath and IconPath commands
to ImagePath commands and removes any directories that are compiled
into fvwm.
Paths starting with a dollar sign are also removed.
.TP 4
.B ModulePath
In fvwm 2.4x, the ModulePath is compiled into fvwm.
.B fvwm24_convert
removes any ModulePath commands it finds.
If you are using your own modules, (not the ones that come with fvwm),
you will have to fix your configuration file after using
.B fvwm24_convert.
.TP 4
.B HilightColor
In fvwm 2.4, the HighlightColor command is replaced by a Style command
using the HilightFore and HilightBack arguments.
.B fvwm24_convert
makes these changes.
.TP 4
.B WindowFont
In fvwm 2.4, the WindowFont command is replaced by a Style command
using the Font argument.
.B fvwm24_convert
makes this change.
.TP 4
.B ColorLimit
In fvwm 2.4, the ColorLimit command is automatic.  If you have a limited
colormap, color limiting is the default.
.B fvwm24_convert
removes any ColorLimit command that it finds.
.TP 4
.B GlobalOpts
The GlobalOpts command is converted to
.B Style
options and the
.B BugOpts
command.
.TP 4
.B Read
Prints a message identifying any read commands found.  The files
being read my need to be converted also.
.SH BUGS

You need Perl to be installed.

.I WindowFont
and
.I HilightColor
commands embedded in functions are not found.
If you have either of these commands in functions, they are not detected.

Known bugs can be found in the fvwm bug tracking system (accessible
from the fvwm home page).

Bug reports can be sent to the fvwm-workers mailing list (see the
.IR FAQ ).

.SH AUTHOR
Dan Espen <despen@telcordia.com>.
