.TH FVWMRC_CONVERT 1x
.SH NAME
fvwmrc_convert \- convert FVWM 1.xx config file to FVWM 2.xx style
.SH SYNOPSIS
/fBfvwmrc_convert/fR [/fIsource/fR [/fIdest\fR]]
.SH DESCRIPTION
.B fvwmrc_convert
is a simple program that tries to convert an FVWM 1.xx configuration
file into an FVWM 2.xx compatible format.  It is not perfect,
especially with regards to Mouse and Key commands, but it provides a
basically-working \fI.fvwm2rc\fR file which can be further modified at
leisure.
.PP
By default, the program will convert \fI~/.fvwmrc\fR, saving the
results in \fI~/.fvwm2rc\fR.  Different source and destination files
may be given, with a destination of `-' meaning standard output.  If
the destination file already exists, it will be backed up first to
\fI~/.fvwm2rc.bak\fR (with whatever the destination file is called
replacing \fI~/.fvwm2rc\fR).
.SH "SEE ALSO"
fvwmrc_convert_allusers
.SH AUTHOR
This manual page was written by Julian Gilbey <jdg@debian.org>.
