'\" t
.\" @(#)xpmroot.1	1.01 8/10/93
.TH XPMROOT 1 "3 July 2001"
.UC

.SH NAME
xpmroot \- Sets the root window of the current X display to an Xpm pixmap

.SH SYNOPSIS
.B xpmroot
\".RB [ \-np ]
\".RB [ \-d ]
\".RB [ \-e ]
.I file

.SH DESCRIPTION
.I xpmroot
reads the Xpm file specified in the command line and displays it in the
root window.

\".SH OPTIONS
\"These command line options are recognized by xpmroot:
\".TP
\".BI "-np"
\"Causes xpmroot to NOT keep the Xpm pixmap in permanent memory under
\"the _XSETROOT_ID property (_XSETROOT_ID is set to None).
\".TP
\".BI "-d"
\"Causes xpmroot to NOT set the background but to free the memory
\"associated with the _XSETROOT_ID property (if any).
\"In any case the _XSETROOT_ID property is set to None and some programs
\"(the fvwm2 modules) may use this to update their background if the background
\"is transparent.
\".TP
\".BI "-fe"
\"Causes xpmroot to free the memory associated with the ESETROOT_PMAP_ID
\"property. This is useful if you  alternately use xpmroot and an
\"Esetroot compatible program.

.SH BUGS
Repeated use of xpmroot with different xpm pixmaps will use up slots in
your color table pretty darn fast.

.SH AUTHOR
Rob Nation
