# Autogenerated from the fvwm sources.
#
# Usage in perl scripts:
#   use vars qw(@EXPORT);
#   require FVWM::Constants;
#
use constant ON_EXIT => '1e20';
use constant INTSIZE => 4;
@EXPORT = qw(
	ON_EXIT
	INTSIZE
);
1;
