.\" t
.\" @(#)FvwmConsole.1x	7/16/96
.TH FvwmConsole 1x "July 16 1996"
.UC

.SH NAME
FvwmConsole \- an FVWM command input interface

.SH SYNOPSIS
FvwmConsole is spawned by fvwm, so no command line invocation will work.

.SH DESCRIPTION
FvwmConsole allows the user to type fvwm configuration commands
interactively, and have them executed immediately.  This tool is
particularly useful for testing new configuration ideas, or for
implementing temporary changes to your environment.

.SH INVOCATION
FvwmConsole must be spawned as a module by fvwm.  FvwmConsole takes all
\fIxterm\fP(1) options, except -name and -title.
.PP
FvwmConsole can be invoked by inserting the line 'Module FvwmConsole' in
the .fvwm2rc file.  This can be placed on a line by itself, if
FvwmConsole is to be spawned during fvwm's initialization, or can be
bound to a menu or mouse button or keystroke to invoke it later.  Fvwm
will search directory specified in the ModulePath configuration option
to attempt to locate FvwmConsole.

.SH CONFIGURATION OPTIONS
FvwmConsole uses \fIxterm\fP(1).  All resources set for xterm are
inherited unless overridden by command line options.

.RS
Module FvwmConsole -g 40x10 -fg black -bg green3
.RE

The option -e can be used to choose an alternate front-end:

.RS
Module FvwmConsole -e /usr/X11/lib/fvwm2/FvwmConsoleC.pl
.RE

(see \fIFvwmConsoleC.pl\fP(1)).
.PP
Also X resources can be set in your ~/.Xdefaults file:

.RS
FvwmConsole*VT100*geometry: 40x4
.br
FvwmConsole*font: 7x14
.RE


.SH "COMMAND EDITING"

There are a few options.  If the GNU readline library is available, it
can be used.
.PP
If Perl5 is installed, FvwmConsoleC.pl can be used as a command editor.
This can be accomplished by either copying FvwmConsoleC.pl 
to fvwmlib directory as FvwmConsoleC or
invoking FvwmConsole with -e option.
For example:

.RS
Module FvwmConsole -e /usr/lib/X11/fvwm2/FvwmConsoleC.pl
.RE

If neither one is installed, a simple input reading function which
doesn't have editing capabilities is used.
.P
GNU readline and FvwmConsoleC.pl have some frequent used commands
in common as default.
These commands are similar to emacs. 
For more details, refer GNU readline man and info pages, and
FvwmConsoleC.pl man page.

.RS
.PD 0
.TP 8
Cntl-A
- beginning of line
.TP
Cntl-B
- previous char
.TP
Cntl-D
- delete char
.TP
Cntl-E
- end of line
.TP
Cntl-F
- next char
.TP
Cntl-H
- backspace
.TP 
Cntl-K
- erase to the end of line
.TP
Cntl-N
- next line
.TP
Cntl-P
- previous line
.TP
Cntl-R
- search reverse
.TP
Cntl-U
- delete line
.TP
Meta-B
- previous word
.TP
Meta-F
- next word
.TP
Esc <
- beginning of history
.TP
Esc >
- end of history
.RE
.PD

.SH EXITING

FvwmConsole can be stopped by entering the command "killme" at the command
line, or the EOF character (usually CTRL-D).
.PP
\fBNote!\fP Do not use the "quit" command, as this is an fvwm builtin:
typing "quit" at the FvwmConsole command line will cause fvwm to exit.

.SH COPYRIGHTS
Copyright 1996, Toshi Isogai. No guarantees or warranties are provided.
Use this program at your own risk. Permission to use this program for
any purpose is given, as long as the copyright is kept intact. 

.SH SEE ALSO
\fIxterm\fP(1), \fIFvwmConsoleC.pl\fP(1), GNU Readline library

.SH AUTHOR
Toshi Isogai  
