#!/usr/bin/perl -w

# This module opens a flash window for one second when page is changed.
# Run and stop it from fvwm as:
#     Module /path/to/module-flash
#     KillModule /path/to/module-flash

use lib `fvwm-perllib dir`;
use FVWM::Module;

sub gotNewPage {
	my ($module, $event) = @_;

	my $width  = $event->_vp_width;
	my $height = $event->_vp_height;

	if (!$width || !$height) {
		# this may happen when doing DeskTopSize 1x1 on page 2 2
		return;
	}
	my $page_nx = int($event->_vp_x / $width);
	my $page_ny = int($event->_vp_y / $height);

	# actually show the flash
	$module->send("Exec xmessage -name FlashWindow " .
		"-bg rgb:50/a0/d0 -fg white -center -timeout 1 -button '' " .
		"-xrm '*cursorName: none' -xrm '*borderWidth: 2' " .
		"-xrm '*borderColor: rgb:f0/f0/a0' -xrm '*Margin: 12' " .
		"'($page_nx, $page_ny)'");
}

my $module = new FVWM::Module(Mask => M_NEW_PAGE);

# show flash on every page switching
$module->addHandler(M_NEW_PAGE, \&gotNewPage);

# make the FlashWindow special: OnTop, without border, without focus and so on
$module->send("Style FlashWindow UsePPosition, NoTitle, NoHandles, BorderWidth 10, StaysOnTop, WindowListSkip, NeverFocus");

# finally enter event loop
$module->eventLoop;
