#!/usr/bin/perl -w

use strict;
use lib `fvwm-config -p | tr -d '\n'`;
use FVWM::Module;

my $newWindowHandler = sub {
	my $self = shift;
	my $type = shift;
	my @args = @_;
	#$self->sendInfo(0, "Echo M_ADD_WINDOW @args");

	# auto iconify all new windows
	my $winId = $args[0];
	$self->sendInfo($winId, "Iconify true");
};

my $module = new FVWM::Module(
	NAME => "FvwmPerlBasedExample",
	MASK => M_ADD_WINDOW | M_FOCUS_CHANGE,
);
$module->sendInfo(0, "Beep");
$module->sendInfo(0, "All (FvwmConsole) Iconify");
$module->sendInfo(0, "Schedule 60000 KillModule $0");

# auto-iconify new windows
$module->addHandler(M_ADD_WINDOW, $newWindowHandler);
# auto-raise windows
$module->addHandler(M_FOCUS_CHANGE, sub { $_[0]->sendInfo($_[2], "Raise") });

$module->eventLoop();
