#!/bin/sh
# Find fvwm commands from function.c struct functions
# Written by Toshi Isogai

echo "# $ff"
echo "# Collection of fvwm2 builtin commands for FvwmCommand"
echo ""

echo "alias FvwmCommand='$1/FvwmCommand'"
echo 'AM () { '
echo 'FvwmCommand "+ $*"'
echo '}'


awk 'OFS="";
    /struct function/,/""/ {
 
	if( $0 ~ /\{ *"[a-zA-Z_]/ ) {
		sub(/^ *\{ *"/,"",$0); 
		sub(/".*/,"",$0);
		print  $0," () {"
		print  "FvwmCommand \"",$0," $*\""
        print  "}" ;
	}
}'



