#!/bin/sh
# Find fvwm commands from function.c struct functions
# Written by Toshi Isogai

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

echo "# $ff"
echo "# Collection of fvwm builtin commands for FvwmCommand"
echo ""

echo "alias FvwmCommand='$1/FvwmCommand'"
echo 'AM () { '
echo '	FvwmCommand "+ $*"'
echo '}'


awk 'BEGIN { OFS=""; }
    /func_type.*\[\]/,/""/ {
        if ( $0 ~ /\{ *"[a-zA-Z_]/ ) {
	  split ( $0, a, "\"" );
	  cmd = a[2];
	  if ( cmd == "function" ) { cmd = "_function"; }
	  if ( cmd == "wait" )     { cmd = "_wait"; }
	  if ( cmd == "exec" )     { cmd = "_exec"; }
	  if ( cmd == "echo" )     { cmd = "_echo"; }
	  print  cmd, " () {"
	  print  "	FvwmCommand \"", a[2], " $*\""
	  print  "}" ;
        }
    }
'
