name: FVWM3 CI ISSUES

on:
    issues:
        types: [ opened, edited, milestoned, closed ]

jobs:
    notification:
        runs-on: ubuntu-latest
        name: notifications
        steps:
            - name: issue notifications
              uses: Gottox/irc-message-action@v1.3.1
              with:
                  server: "irc.libera.chat"
                  notice: true
                  channel: "#fvwm"
                  nickname: fvwm3-gh
                  message: "Issue [${{ github.event.issue.state }}]: [${{ github.event.issue.number }}]: ${{ github.event.issue.title }} -- [${{ github.event.issue.user.login }}]"
